### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Deanskond**
(connecting via http (instead of https) returns HTTP 301, and that json example wasn't exactly correct)

Or just fix this readme without pulling it, so nobody would incorrectly assume that I actually contributed something.

### CODE REVIEW

**Comment by pupgray** [comment]
Haha, good catch! Merging!

**Comment by pupgray** [comment]
Why not pick up some Ruby?~ 👀

**Comment by Deanskond** [comment]
Actually, I was learning Ruby (even Rails specifically) in school, but it was about 10 years ago.

**Comment by pupgray** [comment]
Rails has been pretty stable! I hadn't used rails since about ~6 years ago, but I got back into it pretty quickly. I work with a totally different tech stack on a daily basis, but I'm STILL faster at making stuff in rails, it's great.

**Pull request merged**
